### ISSUE TITLE
react-native peer depencency is old

### ISSUE THREAD

**Issue by alexanderkjeldaas** [wenkesj/react-native-voice#1]

**Comment by wenkesj** [comment]
Yeah, I definitely agree. **PR** is definitely welcome if you want to compare against fork. I would gladly give rights to the npm and github @alexanderkjeldaas

**Comment by wenkesj** [comment]
@hoolymama is 0.33.0 working out?

**Comment by hoolymama** [comment]
Hi @wenkesj The build went okay, which is encouraging. I haven't tried the API yet. I'm dealing with some UI stuff, but later today I will try it and let you know. 

I was quite glad to see a Voice.stop() method, because the other speech recognition package out there only stops when it realises you stopped speaking. I want to have a press and release (walkie-talkie style) UX so I'm hoping it works :)

**Comment by hoolymama** [comment]
Hi @wenkesj It's working fine in react-native 0.33.0. 

To get passed Peer dependency errors I changed the react-native version in package.json, but I'm not sure why I had to. You had specified >0.14.0 and 0.33.0 is greater than 0.14.0. 

Thanks for a great package!

**Comment by BrendanFDMoore** [comment]
@hoolymama The reason the peer dependency was breaking and had to be adjusted is due to React Native still being in major version 0 (as in `0.x.y`), which treats minor version bumps as API breaking changes. 

I pushed a PR here #3 which updates the package to allow a more recent version of React Native, and updated the test app for the changes required past RN 0.29.

**Comment by wenkesj** [comment]
closing this
