### ISSUE TITLE
Terminating with uncaught exception of type NSException

### ISSUE THREAD

**Issue by pratomchaip** [wenkesj/react-native-voice#17]
Just tried running the example app and when calling the Stop/Cancel or Destroy methods, I'm getting:

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[1]'
```
```libc++abi.dylib: terminating with uncaught exception of type NSException```
in
```React/Executors/RCTJSCExecutor.mm```
on line:
```
while (kCFRunLoopRunStopped != CFRunLoopRunInMode(kCFRunLoopDefaultMode, ((NSDate *)[NSDate distantFuture]).timeIntervalSinceReferenceDate, NO)) {
```

Has anyone else come across this bug?

**Comment by wenkesj** [comment]
@pratomchaip Are you receiving this error from the iOS Simulator app?

The main iOS dev - @rudiedev6 - will have more to say about this.

**Comment by rudiedev6** [comment]
@pratomchaip I just ran the lasted version in the simulator and I couldn't replicate that error. Which version of RN do you have?

**Comment by pratomchaip** [comment]
I'm using:
"react": "16.0.0-alpha.3",
"react-native": "0.43.1"

and running it on a device (iPhone) plugged into XCode.

**Comment by evilzug** [comment]
@rudiedev6 @wenkesj:

Same exact problem as @pratomchaip is having, as described above. I call Stop/Cancel/Destroy, and what seems like a very short amount of time later, the app crashes on the exact line above.

"react@16.0.0-alpha.6"
"react-native-cli: 2.0.1"
"react-native: 0.44.0"

using iPhone7-0125 plugged into XCode.

Would love to use this library because it works so well on android, but currently as a result of this issue, there's no way to stop voice detection on iOS... the 'end' event never gets called, and the voice detection keeps detecting.

**Comment by wenkesj** [comment]
Hmm... I am trying to find time to look into this, maybe @rudiedev6 understands this better in the mean time.

**Comment by dgurns** [comment]
Having same issue here.

**Comment by ohtangza** [comment]
@rudiedev6 Can you tell me which version of RN you are using? If it's higher than 0.44, I'll try to upgrade mine and give it a try!

**Comment by mrwordev** [comment]
Ant update on this issue?
I still got this:
```
'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[1]'
```

**Comment by ohtangza** [comment]
@mrwordev I was experiencing a similar issue, so I upgraded my RN. Then, the problem was gone! (RN0.44 --> RN0.46.4)

**Comment by wenkesj** [comment]
Closing in favor of this ^^
